[metadata.heroku]
  root-package = "github.com/smmx/AcCatalog"
  go-version = "1.12.4"
  install = [ "./..." ]
  ensure = true

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[prune]
  go-tests = true
  unused-packages = true
